### PR TITLE
Laravel 11

### PR DESCRIPTION
**Pull request by RhysLees**

### CODE REVIEW

**Comment by azim-kordpour** [comment]
Hi,
I need this package to be compatible with laravel 11.
When will this PR be merged?

**Comment by StanBarrows** [comment]
@azim-kordpour 

v4.2 is published

**Comment by azim-kordpour** [comment]
@StanBarrows thank you

> Illuminate\Filesystem\FilesystemAdapter::Illuminate\Filesystem\{closure}(): Argument #1 ($attributes) must be of type League\Flysystem\StorageAttributes, array given, called in /var/www/html/vendor/league/flysystem/src/DirectoryListing.php on line 33

But I'm getting this error. Do you have an idea?

**Comment by StanBarrows** [comment]
Hey @azim-kordpour 

Can you open a Bug report with a little more details about your configuration? or at what action you receive this error?

**Pull request merged**
